apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        # Eventually auto-injected
        {{ template "mindaro.pod.volumes" . }}
      initContainers:
        # Eventually auto-injected
        {{ template "mindaro.pod.initcontainers" . }}
      containers:
        # Eventually auto-injected
        {{ template "mindaro.pod.containers" . }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            {{- $root := . }}
            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $ref | upper }}_{{ $key | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.fullname" $root }}-{{ $ref }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          # Eventually auto-removed
          {{- if or (not .Values.mindaro) .Values.mindaro.keepHealthChecks }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          # Eventually auto-injected
          {{ template "mindaro.pod.container" . }}
      # Eventually auto-injected
      {{ template "mindaro.pod" . }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
